### ISSUE TITLE
USER_PLUGIN=db and mta auth

### ISSUE THREAD

**Issue by stefangries** [mlan/docker-postfix-amavis#6]
Hello all,

First of all, thank you for the great work. What I really like about this project is that, unlike kopano-docker, there are much fewer containers, making it much easier to roll out. Thanks!

Now my question: I am migrating a kopano installation to docker. I want to use mlan/kopano together with mlan/postfix-amavis. So far I don't use LDAP or AD and don't want to. Therefore I configured kopano with USER_PLUGIN=db. For my small environment this is sufficient.

How can I configure mlan/postfix-amavis to get the users from the database and not from LDAP? So far for my non-docker installation I have done it like this:

In postfix's main.cf: 
`virtual_alias_maps = mysql:/etc/postfix/mysql-users.cf`

In mysql-users.cf
```
user = zarafa
password = secret
hosts = 127.0.0.1
dbname = kopano
query = select value from objectproperty where objectid=(select objectid from objectproperty where value='%s' limit 1) and propname='loginname';
```

Is there a better out-of-the-box way to do this integrated in mlan/postfix-amavis, or have I to do it like described above?

**Comment by mlan** [comment]
@osnet
Excellent! Many thanks for sharing your deep insights.

@stefangries  
If you are able, please outline how your non-docker solution allowed postfix to lookup valid email addresses. Was it limited to email addresses conforming to `<kopano user name>@<domain>`? If it was, then perhaps the remote IMAP approach will work for you, as @osnet suggest above.
You are more than welcome to come back here and post your findings.

I will transfer this issue to [mlan/docker-postfix-amavis](https://github.com/mlan/docker-postfix-amavis)

**Comment by osnet** [comment]
mmh if he wants to use mysql alias db
why not ?
with docker network you can access the db from mta just like the app does would be less effort

**Comment by stefangries** [comment]
I have started with the tests now and use the docker-compose.yaml below. What is strange about it: For the MTA I neither use authentication by password file, LDAP or IMAP. The documentation notes:

`To avoid the risk of being an open relay the SMTPS and submission (MSA) services are only activated when at least one SASL method has activated.
`

But sending mails via webapp works. Isn't this strange?

Or does this configuration only affect incoming mails? And if it only affects incoming mails, why can't you just enable mails with a recipient à la ****@myhost.net instead of account-lookups?

```
version: '3'

services:
  app:
    image: mlan/kopano
    networks:
      - kopano-net
    ports:
      - "127.0.0.1:8008:80"    # WebApp & EAS (alt. HTTP)
      - "127.0.0.1:143:143"    # IMAP (not needed if all devices can use EAS)
      - "127.0.0.1:110:110"    # POP3 (not needed if all devices can use EAS)
      - "127.0.0.1:8080:8080"  # ICAL (not needed if all devices can use EAS)
      - "127.0.0.1:993:993"    # IMAPS (not needed if all devices can use EAS)
      - "127.0.0.1:995:995"    # POP3S (not needed if all devices can use EAS)
      - "127.0.0.1:8443:8443"  # ICALS (not needed if all devices can use EAS)
    depends_on:
      - db
      - mta
    environment: # Virgin config, ignored on restarts unless FORCE_CONFIG given.
      - USER_PLUGIN=db
      - MYSQL_HOST=${MYSQL_HOST-db}
      - SMTP_SERVER=mta
      - MYSQL_DATABASE=${MYSQL_DATABASE-kopano}
      - MYSQL_USER=${MYSQL_USER-kopano}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD-secret}
      - IMAP_LISTEN=*:143                       # also listen to eth0
      - POP3_LISTEN=*:110                       # also listen to eth0
      - ICAL_LISTEN=*:8080                      # also listen to eth0
      - IMAPS_LISTEN=*:993                      # enable TLS
      - POP3S_LISTEN=*:995                      # enable TLS
      - ICALS_LISTEN=*:8443                     # enable TLS
      - PLUGIN_SMIME_USER_DEFAULT_ENABLE_SMIME=true
      - SYSLOG_LEVEL=${SYSLOG_LEVEL-3}
      - LOG_LEVEL=${LOG_LEVEL-3}
    volumes:
      - app-conf:/etc/kopano
      - app-atch:/var/lib/kopano/attachments
      - app-sync:/var/lib/z-push
      - app-spam:/var/lib/kopano/spamd          # kopano-spamd integration
    cap_add: # helps debugging by allowing strace
      - sys_ptrace

  mta:
    image: mlan/postfix-amavis
    hostname: ${MAIL_SRV-mx}.${MAIL_DOMAIN-example.com}
    networks:
      - kopano-net
    ports:
      - "127.0.0.1:25:25"      # SMTP
      - "127.0.0.1:465:465"    # SMTPS authentication required
    environment: # Virgin config, ignored on restarts unless FORCE_CONFIG given.
      - MESSAGE_SIZE_LIMIT=${MESSAGE_SIZE_LIMIT-25600000}
      - VIRTUAL_TRANSPORT=lmtp:app:2003
      - SMTP_TLS_WRAPPERMODE=${SMTP_TLS_WRAPPERMODE-no}
      - SMTPD_USE_TLS=yes
      - REGEX_ALIAS=${REGEX_ALIAS-}
      - DKIM_SELECTOR=${DKIM_SELECTOR-default}
      - SA_TAG_LEVEL_DEFLT=${SA_TAG_LEVEL_DEFLT-2.0}
      - SA_DEBUG=${SA_DEBUG-0}
      - SYSLOG_LEVEL=${SYSLOG_LEVEL-}
      - LOG_LEVEL=${LOG_LEVEL-0}
      - RAZOR_REGISTRATION=${RAZOR_REGISTRATION-}
    volumes:
      - mta:/srv
      - app-spam:/var/lib/kopano/spamd          # kopano-spamd integration
    cap_add: # helps debugging by allowing strace
      - sys_ptrace

  db:
    image: mariadb
    command: ['--log_warnings=1']
    networks:
      - kopano-net
    environment:
      - LANG=C.UTF-8
      - MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD-secret}
      - MYSQL_DATABASE=${MYSQL_DATABASE-kopano}
      - MYSQL_USER=${MYSQL_USER-kopano}
      - MYSQL_PASSWORD=${MYSQL_PASSWORD-secret}
    volumes:
      - db:/var/lib/mysql

networks:
  kopano-net:

volumes:
  app-atch:
  app-conf:
  app-spam:
  app-sync:
  auth:
  db:
  mta:
```
